theme: minima
title: KBS' Hub
author: KBS-SE
description: "A little about me and my work"
sass:
  sass_dir: _sass
  style: compressed  # Set to "expanded" during development for human-readable CSS
